apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/test-nodeapp@sha256:9aedfe90d6c97c69885ffa919fcdf5814f2047e4cab2ed9371cb8f93990ad69d
        name: container-image
        resources: {}
status: {}
